### ISSUE TITLE
List all kinds of tags in tags file

### ISSUE THREAD

**Issue by devonliu02** [arnaud-lb/vim-php-namespace#28]
It list all kinds of tags in my tags file when i press `<leader>u`, even the variables, functions.
How could i fix it?

![image](https://cloud.githubusercontent.com/assets/4284940/22468514/790abee4-e803-11e6-9c3c-4ee9f5156073.png)

**Comment by arnaud-lb** [comment]
I remember trying to fix that, but I couldn't find a way to tell vim to list only classes.

However, it's less a problem in case-sensitive mode, because searching for the tag `User` doesn't find variables named `user` in this mode.

I would suggest to switch to case sensitive mode.

**Comment by arnaud-lb** [comment]
Also, you might be able to exclude variable names from you tags file by adding `--php-kinds=-v` to your ctags command (this excludes variables from the tags file).

**Comment by robertbasic** [comment]
I have `--PHP-kinds=+cfit-va` in my global ctags file - `~/.ctags` - and it made `vim-php-namespace` much better!

Thanks for the great plugin!
