### ISSUE TITLE
Where to place the tag file

### ISSUE THREAD

**Issue by Croxarens** [arnaud-lb/vim-php-namespace#30]
After the installation, where should I place the file "_tag_" generated by the command `ctags -R --PHP-kinds=cfi`?

**Comment by arnaud-lb** [comment]
Usually the tags file is placed at the root of the project. By default, vim searches in the directory of the current file, and in the current working directory (if both exist, it uses both). This can be controlled with the `'tags'` option: http://vimdoc.sourceforge.net/htmldoc/options.html#'tags'.

**Comment by Croxarens** [comment]
Thanks so much @arnaud-lb
