### ISSUE TITLE
support for re-ordering imports

### ISSUE THREAD

**Issue by arnaud-lb** [arnaud-lb/vim-php-namespace#5]
Add support for re-ordering imports

**Comment by mikedfunk** [comment]
```
" sort php use statements and return to where you were
command! SortUse execute "normal! msgg/use\ <cr>vip:sort<cr>\`s:delmarks s<cr>:nohlsearch<cr>:echo 'sorted use statements'<cr>"
nnoremap <leader>su :SortUse<cr>
```

**Comment by greg0ire** [comment]
The current code for insert looks like this : 

```
 " insert after last use or namespace or <?php
if search('^use\_s\_[[:alnum:][:blank:]\\_]*;', 'be') > 0
    call append(line('.'), use)
elseif search('^\s*namespace\_s\_[[:alnum:][:blank:]\\_]*[;{]', 'be') > 0
    call append(line('.'), "")
    call append(line('.')+1, use)
elseif search('<?\%(php\)\?', 'be') > 0
    call append(line('.'), "")
    call append(line('.')+1, use)
else
    call append(1, use)
endif
```

After this gets executed, we are sure that there is at least one `use` statement.
I guess we could call `search('^use\_s\_[[:alnum:][:blank:]\\_]*;', 'be')` again (if `be` means "from the beginning"), and then call sort on the current §, so if anyone knows how to do that…

**Comment by greg0ire** [comment]
In fact, it is a bad idea, the sort should be callable even when not inserting anything.

**Comment by greg0ire** [comment]
I have [a work in progress on my fork](https://github.com/greg0ire/vim-php-namespace/tree/sort). It is very basic ATM, there are more edge cases to handle I guess, but it is a start. It defines a new method that sorts use statements. Works only if they are already isolated in one paragraph.

**Comment by greg0ire** [comment]
Edge cases I can think of and my solution does not handle (yet) :

```php
<?php
namespace Foo;

use Baz;
use Bar; // no newline after that
class FooBar
{
}
```

```php
<?php
namespace Foo;

use Baz;

use Bar;


class FooBar
{
}
```

```php
<?php
namespace Foo;

class FooBar
{
    use MyTrait;
}
```
